### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by iamredeye** [johnno1962/Xtrace#11]
Hello,

I tried to compile the xtrace library classes for an app with arm64 architecture but no success.
I had seen in the code this condition :
# ifdef **arm64**

// make this into #warning to switch between the simulator and a device more easily
//#error Xtrace will not work on an ARM64 build. Rebuild for $(ARCHS_STANDARD_32_BIT).

I commented it but have faced SIGABT exceptions with arm64 devices.

Is there a solution for this issue please ?

Thanks

**Comment by winster** [comment]
Hi,

Without it works fine with simulator. But I want to run it with the new devices. Is there any other library that works for ARM64?

Thanks
Winster
