### ISSUE TITLE
Xtracing Google Chrome / Chromium

### ISSUE THREAD

**Issue by mblsha** [johnno1962/Xtrace#12]
Xtracing Google Chrome / Chromium doesn't seem to work. I'm attaching to main process using LLDB, loading Xtrace.framework, and trying to ```xtrace``` on something, and it immediately fails with an exception.

```
(lldb) p (BOOL)[[NSBundle bundleWithPath:@"/Library/Frameworks/Xtrace.framework"] load]
(BOOL) $0 = YES
(lldb) p (id)[[NSObject alloc] init]
(id) $1 = 0x000062000001df30
(lldb) p (void)[$1 xtrace]
error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x2aa983abec0).
The process has been returned to the state before expression evaluation.
```

Tried doing the same in a custom Chromium build, and it reports this error:

```
[6197:1815:0225/220057:FATAL:chrome_browser_application_mac.mm(148)] Someone is trying to raise an exception!  NSInvalidArgumentException reason NSGetSizeAndAlignment(): unsupported type encoding spec 'b' at 'b1b31}}8' in '{?=ddd{?=b1b31}}8'
```

What's the best way to troubleshoot this?

**Comment by johnno1962** [comment]
Hi Michail, you’re better better on finding out what is happening by building from source and avoiding tracing NSObject which is a little close to the system to be tracing perhaps. Looks like chrome uses a mixture of C++ and Objective-C which might be problematic. I don’t think Xtrace uses NSGetSizeAndAlignment() these days unless it is in [sig getArgumentTypeAtIndex:i].

Sorry I can’t be of any more assistance. It’s all a bit of a hack frankly.

**Comment by mblsha** [comment]
Xtrace is a glorious hack, thanks for creating it — it's really invaluable.

Turns out, Chromium swizzles NSException's init, and freaks out before Xtrace manages to catch it. Disabling swizzling fixes the problem.

The fix:

```
--- a/chrome/browser/chrome_browser_application_mac.mm
+++ b/chrome/browser/chrome_browser_application_mac.mm
@@ -233,6 +233,7 @@ void CancelTerminate() {
 namespace {
 
 void SwizzleInit() {
+  return;
   // Do-nothing wrapper so that we can arrange to only swizzle
   // -[NSException raise] when DCHECK() is turned on (as opposed to
   // replicating the preprocess logic which turns DCHECK() on).
```
