### ISSUE TITLE
No Cocoapods podspec

### ISSUE THREAD

**Issue by rex-remind101** [johnno1962/Xtrace#9]
It would be great if this was available in Cocoapods :smile:

**Comment by mszczepanczyk** [comment]
@johnno1962 What happened to the commit with Podspec? Why hasn't it been merged into master?

**Comment by johnno1962** [comment]
A Podsepc would have required a BSD or MIT license which would not be my choice at the moment.

**Comment by 0xced** [comment]
> A Podsepc would have required a BSD or MIT license

I don’t think so, you can choose [whatever license you want](https://guides.cocoapods.org/making/making-a-cocoapod.html#the-pod-files).

**Comment by MoridinBG** [comment]
Can a Podspec be added, now that the code is MIT licensed?
